# 学習率（learn_rate）
#
#   この将棋エンジンでは、評価値テーブルの編集対象の数を、間引いて残す率です。
#   小さくするほど、１つの棋譜から学ぶ箇所が減って、やっつけになります。
#   分子（numerator）と分母（denominator）を整数で書いてください
#
learn_rate.numerator = 1
learn_rate.denominator = 1 #5

# 短手数の詰めチェックモードでの指し継ぎ手数
# 15 で 1対局20分ぐらい
# 21 で、1対局（23手）の学習に 15 分ぐらい。 21 は終わる
# 31 は 23分で 15手ぐらいしか進んでない。流石に多いか
short_mate_mode.relay_move_number = 27 #31× #21〇 #15〇 #9〇
